config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :services
  resources :user_knowledges
  resources :knowledges
  devise_for :users

  root 'welcome#index'

  resources :professions

end

app/models/user_knowledge.rb
class UserKnowledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :knowledge
end

app/controllers/user_knowledges_controller.rb
class UserKnowledgesController < ApplicationController
  before_action :set_user_knowledge, only: [:show, :edit, :update, :destroy]

  # GET /user_knowledges
  # GET /user_knowledges.json
  def index
    @user_knowledges = UserKnowledge.all
  end

  # GET /user_knowledges/1
  # GET /user_knowledges/1.json
  def show
  end

  # GET /user_knowledges/new
  def new
    @user_knowledge = UserKnowledge.new
  end

  # GET /user_knowledges/1/edit
  def edit
  end

  # POST /user_knowledges
  # POST /user_knowledges.json
  def create
    @user_knowledge = UserKnowledge.new(user_knowledge_params)

    respond_to do |format|
      if @user_knowledge.save
        format.html { redirect_to @user_knowledge, notice: 'User knowledge was successfully created.' }
        format.json { render :show, status: :created, location: @user_knowledge }
      else
        format.html { render :new }
        format.json { render json: @user_knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_knowledges/1
  # PATCH/PUT /user_knowledges/1.json
  def update
    respond_to do |format|
      if @user_knowledge.update(user_knowledge_params)
        format.html { redirect_to @user_knowledge, notice: 'User knowledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_knowledge }
      else
        format.html { render :edit }
        format.json { render json: @user_knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_knowledges/1
  # DELETE /user_knowledges/1.json
  def destroy
    @user_knowledge.destroy
    respond_to do |format|
      format.html { redirect_to user_knowledges_url, notice: 'User knowledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_knowledge
      @user_knowledge = UserKnowledge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_knowledge_params
      params.require(:user_knowledge).permit(:user_id, :knowledge_id, :date)
    end
end

app/helpers/user_knowledges_helper.rb
module UserKnowledgesHelper
end

app/views/user_knowledges/_form.html.erb
<%= form_for(@user_knowledge) do |f| %>
  <% if @user_knowledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_knowledge.errors.count, "error") %> prohibited this user_knowledge from being saved:</h2>

      <ul>
      <% @user_knowledge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :knowledge_id %><br>
    <%= f.text_field :knowledge_id %>
  </div>
  <div class="field">
    <%= f.label :criationDate %><br>
    <%= f.datetime_select :criationDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_knowledges/edit.html.erb
<h1>Editing User Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_knowledge %> |
<%= link_to 'Back', user_knowledges_path %>

app/views/user_knowledges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Knowledges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Knowledge</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_knowledges.each do |user_knowledge| %>
      <tr>
        <td><%= user_knowledge.user %></td>
        <td><%= user_knowledge.knowledge %></td>
        <td><%= user_knowledge.date %></td>
        <td><%= link_to 'Show', user_knowledge %></td>
        <td><%= link_to 'Edit', edit_user_knowledge_path(user_knowledge) %></td>
        <td><%= link_to 'Destroy', user_knowledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User knowledge', new_user_knowledge_path %>

app/views/user_knowledges/new.html.erb
<h1>New User Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Back', user_knowledges_path %>

app/views/user_knowledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_knowledge.user %>
</p>

<p>
  <strong>Knowledge:</strong>
  <%= @user_knowledge.knowledge %>
</p>

<p>
  <strong>Date:</strong>
  <%= @user_knowledge.date %>
</p>

<%= link_to 'Edit', edit_user_knowledge_path(@user_knowledge) %> |
<%= link_to 'Back', user_knowledges_path %>