config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :services
  resources :user_knowledges
  resources :knowledges
  devise_for :users

  root 'welcome#index'

  resources :professions

end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
  belongs_to :profession
  has_many :users, through: :user_knowledges
end

app/controllers/knowledges_controller.rb
class KnowledgesController < ApplicationController
  before_action :set_knowledge, only: [:show, :edit, :update, :destroy]

  # GET /knowledges
  # GET /knowledges.json
  def index
    @knowledges = Knowledge.all
  end

  # GET /knowledges/1
  # GET /knowledges/1.json
  def show
  end

  # GET /knowledges/new
  def new
    @knowledge = Knowledge.new
  end

  # GET /knowledges/1/edit
  def edit
  end

  # POST /knowledges
  # POST /knowledges.json
  def create
    @knowledge = Knowledge.new(knowledge_params)

    respond_to do |format|
      if @knowledge.save
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge }
      else
        format.html { render :new }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledges/1
  # PATCH/PUT /knowledges/1.json
  def update
    respond_to do |format|
      if @knowledge.update(knowledge_params)
        format.html { redirect_to @knowledge, notice: 'Knowledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge }
      else
        format.html { render :edit }
        format.json { render json: @knowledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledges/1
  # DELETE /knowledges/1.json
  def destroy
    @knowledge.destroy
    respond_to do |format|
      format.html { redirect_to knowledges_url, notice: 'Knowledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge
      @knowledge = Knowledge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def knowledge_params
      params.require(:knowledge).permit(:description, :profession_id)
    end
end

app/helpers/knowledges_helper.rb
module KnowledgesHelper
end

app/views/knowledges/_form.html.erb
<%= form_for(@knowledge) do |f| %>
  <% if @knowledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@knowledge.errors.count, "error") %> prohibited this knowledge from being saved:</h2>

      <ul>
      <% @knowledge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :profession_id %><br>
    <%= f.text_field :profession_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/knowledges/edit.html.erb
<h1>Editing Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @knowledge %> |
<%= link_to 'Back', knowledges_path %>

app/views/knowledges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Knowledges</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Profession</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @knowledges.each do |knowledge| %>
      <tr>
        <td><%= knowledge.description %></td>
        <td><%= knowledge.profession %></td>
        <td><%= link_to 'Show', knowledge %></td>
        <td><%= link_to 'Edit', edit_knowledge_path(knowledge) %></td>
        <td><%= link_to 'Destroy', knowledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Knowledge', new_knowledge_path %>

app/views/knowledges/new.html.erb
<h1>New Knowledge</h1>

<%= render 'form' %>

<%= link_to 'Back', knowledges_path %>

app/views/knowledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @knowledge.description %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @knowledge.profession %>
</p>

<%= link_to 'Edit', edit_knowledge_path(@knowledge) %> |
<%= link_to 'Back', knowledges_path %>